# Auto-generated by compose2nix.

{ pkgs, lib, config, ... }:
let
    host_base_config_path = "/mnt/storage/servarr-config";
    host_base_data_path = "/mnt/storage/data";
in
{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."flaresolverr" = {
    image = "ghcr.io/flaresolverr/flaresolverr:latest";
    environment = {
      "LOG_LEVEL" = "info";
      "PGID" = "1000";
      "PUID" = "1000";
      "TZ" = "UTC";
    };
    volumes = [
      "${host_base_data_path}/flaresolverr:/config:rw"
    ];
    ports = [
      "8191:8191/tcp"
    ];
    dependsOn = [
      "vpn"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=flaresolverr"
      "--network=servarr-project_media-network"
    ];
  };
  systemd.services."docker-flaresolverr" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-servarr-project_media-network.service"
    ];
    requires = [
      "docker-network-servarr-project_media-network.service"
    ];
    partOf = [
      "docker-compose-servarr-project-root.target"
    ];
    wantedBy = [
      "docker-compose-servarr-project-root.target"
    ];
  };
  virtualisation.oci-containers.containers."jellyfin" = {
    image = "jellyfin/jellyfin";
    environment = {
      "PGID" = "1000";
      "PUID" = "1000";
      "TZ" = "UTC";
    };
    volumes = [
      "${host_base_data_path}/media:/media:rw"
      "${host_base_config_path}/jellyfin/cache:/cache:rw"
      "${host_base_config_path}/jellyfin/config:/config:rw"
    ];
    ports = [
      "8096:8096/tcp"
      "7359:7359/udp"
      "8920:8920/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=jellyfin"
      "--network=servarr-project_media-network"
    ];
  };
  systemd.services."docker-jellyfin" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-servarr-project_media-network.service"
    ];
    requires = [
      "docker-network-servarr-project_media-network.service"
    ];
    partOf = [
      "docker-compose-servarr-project-root.target"
    ];
    wantedBy = [
      "docker-compose-servarr-project-root.target"
    ];
  };
  virtualisation.oci-containers.containers."prowlarr" = {
    image = "ghcr.io/hotio/prowlarr";
    environment = {
      "PGID" = "1000";
      "PUID" = "1000";
      "TZ" = "UTC";
    };
    volumes = [
      "${host_base_config_path}/prowlarr:/config:rw"
    ];
    ports = [
      "9696:9696/tcp"
    ];
    dependsOn = [
      "vpn"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=prowlarr"
      "--network=servarr-project_media-network"
    ];
  };
  systemd.services."docker-prowlarr" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-servarr-project_media-network.service"
    ];
    requires = [
      "docker-network-servarr-project_media-network.service"
    ];
    partOf = [
      "docker-compose-servarr-project-root.target"
    ];
    wantedBy = [
      "docker-compose-servarr-project-root.target"
    ];
  };
  virtualisation.oci-containers.containers."radarr" = {
    image = "ghcr.io/hotio/radarr";
    environment = {
      "PGID" = "1000";
      "PUID" = "1000";
      "TZ" = "UTC";
    };
    volumes = [
      "${host_base_data_path}:/data:rw"
      "${host_base_config_path}/radarr:/config:rw"
    ];
    ports = [
      "7878:7878/tcp"
    ];
    dependsOn = [
      "vpn"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=radarr"
      "--network=servarr-project_media-network"
    ];
  };
  systemd.services."docker-radarr" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-servarr-project_media-network.service"
    ];
    requires = [
      "docker-network-servarr-project_media-network.service"
    ];
    partOf = [
      "docker-compose-servarr-project-root.target"
    ];
    wantedBy = [
      "docker-compose-servarr-project-root.target"
    ];
  };
  virtualisation.oci-containers.containers."sonarr" = {
    image = "ghcr.io/hotio/sonarr";
    environment = {
      "PGID" = "1000";
      "PUID" = "1000";
      "TZ" = "UTC";
    };
    volumes = [
      "${host_base_data_path}:/data:rw"
      "${host_base_config_path}/sonarr:/config:rw"
    ];
    ports = [
      "8989:8989/tcp"
    ];
    dependsOn = [
      "vpn"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=sonarr"
      "--network=servarr-project_media-network"
    ];
  };
  systemd.services."docker-sonarr" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-servarr-project_media-network.service"
    ];
    requires = [
      "docker-network-servarr-project_media-network.service"
    ];
    partOf = [
      "docker-compose-servarr-project-root.target"
    ];
    wantedBy = [
      "docker-compose-servarr-project-root.target"
    ];
  };
  virtualisation.oci-containers.containers."transmission" = {
    image = "lscr.io/linuxserver/transmission:latest";
    environment = {
      "PGID" = "1000";
      "PUID" = "1000";
      "TRANSMISSION_DOWNLOAD_DIR" = "/data/downloads/complete";
      "TRANSMISSION_INCOMPLETE_DIR" = "/data/downloads/incomplete";
      "TZ" = "UTC";
    };
    volumes = [
      "${host_base_data_path}/downloads:/data/downloads:rw"
      "${host_base_config_path}/transmission:/config:rw"
    ];
    dependsOn = [
      "vpn"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network=container:vpn"
    ];
  };
  systemd.services."docker-transmission" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    partOf = [
      "docker-compose-servarr-project-root.target"
    ];
    wantedBy = [
      "docker-compose-servarr-project-root.target"
    ];
  };

  sops.templates."container-env.env".content = ''
    VPN_SERVICE_PROVIDER=protonvpn
    VPN_TYPE=wireguard
    WIREGUARD_PRIVATE_KEY="${config.sops.placeholder.wireguard_private_key}"
  '';

  virtualisation.oci-containers.containers."vpn" = {
    image = "qmcgaw/gluetun";
    environmentFiles = [
      config.sops.templates."container-env.env".path
    ];
    ports = [
      "9091:9091/tcp"
      "51413:51413/tcp"
      "51413:51413/udp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--cap-add=NET_ADMIN"
      "--device=/dev/net/tun:/dev/net/tun:rwm"
      "--network-alias=vpn"
      "--network=servarr-project_media-network"
    ];
  };
  systemd.services."docker-vpn" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-servarr-project_media-network.service"
    ];
    requires = [
      "docker-network-servarr-project_media-network.service"
    ];
    partOf = [
      "docker-compose-servarr-project-root.target"
    ];
    wantedBy = [
      "docker-compose-servarr-project-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-servarr-project_media-network" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f servarr-project_media-network";
    };
    script = ''
      docker network inspect servarr-project_media-network || docker network create servarr-project_media-network
    '';
    partOf = [ "docker-compose-servarr-project-root.target" ];
    wantedBy = [ "docker-compose-servarr-project-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-servarr-project-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
