creation_rules:
  - path_regex: secrets/.*\.yaml$
    key_groups:
      - age:
          - "age1ptzakth0xwsc0s3h9kx9jgzmkmdarl3rz5v2vgkx6cy4mj0uma2slhtqdq" # system ssh pub key
          - "age1vk7dacx3t2vpw3308j4wywhpu076rkwgav8xjlvp0q0e35zmsv8qk8ml2d" # for user patroclus
