# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "rpool/root";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/B8CB-5E4B";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/disks/disk1" =
    { device = "/dev/disk/by-uuid/778517ef-0b29-499b-b831-9674b6f79c2a";
      fsType = "ext4";
    };

  fileSystems."/disks/disk2" =
    { device = "/dev/disk/by-uuid/0f56859b-290f-482f-9abc-27d5fa544578";
      fsType = "ext4";
    };

  fileSystems."/mnt/disks/disk1" =
    { device = "/disks/disk1";
      fsType = "none";
      options = [ "bind" ];
    };

  fileSystems."/mnt/disks/disk2" =
    { device = "/disks/disk2";
      fsType = "none";
      options = [ "bind" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
